name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Puedes ajustar la versión de Node.js según tus necesidades

    - name: Install dependencies
      run: npm install

    - name: Build the site
      run: npm run build # Asumiendo que tienes un script de build en tu package.json, puedes omitir este paso si no es necesario

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: main
        publish_dir: ./ # Directorio que contiene tus archivos HTML, CSS y JS
